--Users 테이블 입니다.
CREATE TABLE PUSERS (
 ID VARCHAR2(50) PRIMARY KEY,
 PID VARCHAR2(50),
 PWD VARCHAR2(100) NOT NULL,
 NAME VARCHAR2(20) NOT NULL,
 PHONE VARCHAR2(30) NOT NULL,
 ADDR VARCHAR2(100) NOT NULL,
 FAVORITE VARCHAR2(300),
 EMAIL VARCHAR2(100),
 NAVEREMAIL VARCHAR2(100),
 UNIQID VARCHAR2(30),
 ISADMIN VARCHAR2(4),	--관리자 인지 판단
 DISABLED VARCHAR2(5),   --정지 회원인지 판단
 REGDATE DATE
 );
 
